// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfaw8I-rwXu8j0El340yIGr-N2agTzp6c',
    appId: '1:1077070194300:web:eb4fc5b69fb9c51c96f5eb',
    messagingSenderId: '1077070194300',
    projectId: 'crystalgrimoire-v3-production',
    authDomain: 'crystalgrimoire-v3-production.firebaseapp.com',
    storageBucket: 'crystalgrimoire-v3-production.appspot.com',
    measurementId: 'G-B2QJY94ZQ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfaw8I-rwXu8j0El340yIGr-N2agTzp6c',
    appId: '1:1077070194300:android:eb4fc5b69fb9c51c96f5eb',
    messagingSenderId: '1077070194300',
    projectId: 'crystalgrimoire-v3-production',
    storageBucket: 'crystalgrimoire-v3-production.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfaw8I-rwXu8j0El340yIGr-N2agTzp6c',
    appId: '1:1077070194300:ios:eb4fc5b69fb9c51c96f5eb',
    messagingSenderId: '1077070194300',
    projectId: 'crystalgrimoire-v3-production',
    storageBucket: 'crystalgrimoire-v3-production.appspot.com',
    iosBundleId: 'com.clearseasolutions.crystalgrimoire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfaw8I-rwXu8j0El340yIGr-N2agTzp6c',
    appId: '1:1077070194300:ios:eb4fc5b69fb9c51c96f5eb',
    messagingSenderId: '1077070194300',
    projectId: 'crystalgrimoire-v3-production',
    storageBucket: 'crystalgrimoire-v3-production.appspot.com',
    iosBundleId: 'com.clearseasolutions.crystalgrimoire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfaw8I-rwXu8j0El340yIGr-N2agTzp6c',
    appId: '1:1077070194300:web:eb4fc5b69fb9c51c96f5eb',
    messagingSenderId: '1077070194300',
    projectId: 'crystalgrimoire-v3-production',
    authDomain: 'crystalgrimoire-v3-production.firebaseapp.com',
    storageBucket: 'crystalgrimoire-v3-production.appspot.com',
  );

}